### ISSUE TITLE
[ Week 1 ] 1주차 워크북 미션1 Todo List (HTML, CSS, JS)

### ISSUE THREAD

**Issue by hansoojeongsj** [DS-UMC-7th/UMC-7th-Chri#1]
### 🛠 Mission

UMC Study Plan의 Todo List를 만드는 미션입니다. 

### 📝 To-do

- [x]  `제목`, `해야 할 일을 작성할 수 있는 칸`, `해야 할 일/해낸 일을 표시하는 UI`를 만들어 주세요.
- [x]  해야 할 일을 작성할 수 있는 `input 컴포넌트`에 내용을 작성하고, **`ENTER`**를 입력하면 `해야 할 일`에 작성한 할 일이 추가 되도록 해주세요.
- [x]  해야 할 일의 완료를 누르면 해당할 일이 `해낸 일`로 이동하도록 해주세요.
- [x]  해낸 일의 삭제를 누르면 `삭제`되도록 해주세요.

### 🔍 접근 방법

- HTML과 CSS를 사용하여 UI를 구성했습니다. 사용자 입력을 받기 위한 input 필드를 추가했고 해야 할 일과 해낸 일을 구분하는 두 개의 목록(pending-list, completed-list)을 만들었습니다.

- keypress 이벤트를 사용하여 사용자가 Enter 키를 눌렀을 때 할 일을 추가할 수 있도록 했습니다. 사용자가 텍스트를 입력하고 Enter를 누르면 addTask() 함수가 호출되어 할 일 목록에 새로운 항목을 추가합니다.

- 새로운 할 일에는 '완료' 버튼이 추가되고, 누르면 '해낸 일' 목록으로 이동하며 '완료' 버튼은 '삭제' 버튼으로 바뀝니다. moveToCompleted() 함수는 '완료' 버튼을 제거하고 '삭제' 버튼을 추가한 뒤 항목을 이동시키며, deleteTask() 함수는 '삭제' 버튼을 눌렀을 때 항목을 제거합니다.
