### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션1

### ISSUE THREAD

**Issue by hansoojeongsj** [DS-UMC-7th/UMC-7th-Chri#16]
### 🛠 Mission

주어진 BE 서버를 활용하여 회원가입, 로그인 기능을 구현하는 미션입니다. 

### 📝 To-do

회원가입
- [x]  **`회원가입 API`**를 잘 연결하였는가?
- [x]  회원가입 후, `login 페이지`로 이동하였는가?

로그인
- [x]  **`로그인 API`**를 잘 연결하였는가?
- [x]  로그인 후, `메인 페이지`로 이동하였는가?
- [x]  **`AccessToken`**과, **`RefreshToken`**을 **`로컬스토리지에서 저장`**하였는가?

로그인 후 메인 페이지 이동 시
- [x]  **`Navbar`**의 로그인, 회원가입 버튼 대신, **`로그아웃 버튼`**을 보여주었는가?
- [x]  **`유저 정보 불러오기 API`**를 호출하여, 로그인 한 유저 이메일 **`@ 기준 앞 부분(닉네임)`**을 Navbar에 잘 보여주었는가?

로그아웃 시
- [x]  로그아웃 후, Navbar에 유저 정보가, 사라지며, **`로그인, 회원가입 버튼이 다시 생겼는가?`**
- [x]  **`AccessToken`**과, **`RefreshToken`**을 **`로컬스토리지에서 제거`**하였는가?

추가로 해보면 좋아요!
- [ ]  `refreshToken을 활용`**하여,** `토큰 재발급`**을 진행해보세요.**
    - [ ]  **`Axios Interceptor`**를 활용하여, **`refreshToken`**을 활용하여, **`accessToken`**을 **`재발급`** 받는 로직을 구글 검색을 통해, 직접 해결해보세요!
    - [x]  **`refreshToken`**을 활용하여, 토큰 재발급을 진행하면, 어떤 부분에서 이점이 있는지 작성해주세요!

### 🔍 접근 방법

로그인 후 받은 AccessToken과 RefreshToken을 로컬스토리지에 저장하여 페이지 새로고침 시에도 로그인 상태를 유지하도록 했습니다. 로그인한 유저의 이메일에서 @ 앞부분(닉네임)을 불러와 Navbar에 표시하며, 로그아웃 시에는 토큰과 유저 정보를 로컬스토리지에서 제거하고, 로그인과 회원가입 버튼이 다시 나타나도록 처리했습니다.
