### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션2

### ISSUE THREAD

**Issue by hansoojeongsj** [DS-UMC-7th/UMC-7th-Chri#18]
### 🛠 Mission

미션 2. QueryParameter 활용 검색 기능을 구현하는 미션입니다.
여러 조건에 대하여 활용해서 검색 기능을 구현하되, Query-Parmeter를 효율적으로 활용해서 구현해야 합니다.

### 📝 To-do

- [x]  `Styled-Components`를 활용해주세요
- [ ]  기존에 만들었던, `movie-card 컴포넌트`를 재사용해주세요.
- [x] Debounce를 검색 기능에 적용해주세요!

1. 영화 제목 검색어를 입력하지 않는 경우 (/search 경로에 처음 온 경우)
2. 영화 제목 검색어를 입력한 경우
3. 영화 검색어를 입력했으나, 해당 검색어의 영화 데이터가 존재하지 않는 경우.
4. 로딩 중인 경우, 아래와 같은 Skeleton UI를 만들어주세요!
5. Debounce에 대한 키워드를 학습하셨나요?

### 🔍 접근 방법

영화 검색 기능을 구현하기 위해, 처음에는 전체 영화 목록을 불러오고, 검색어 입력 시 Debounce를 적용하여 효율적으로 영화 데이터를 검색하기 위한 요청을 처리합니다. Styled-Components를 사용해 UI 요소들을 스타일링하고, Skeleton UI로 로딩 상태를 표시하여 사용자 경험을 개선합니다. 기존의 movie-card 컴포넌트를 재사용하여 검색 결과를 효율적으로 출력합니다.
