### ISSUE TITLE
[ Week 2 ] 2주차 워크북 미션1, 미션2

### ISSUE THREAD

**Issue by hansoojeongsj** [DS-UMC-7th/UMC-7th-Chri#3]
### 🛠 Mission

- Mission1 - ToDoList CSS
'실습 - ToDoList 만들며 useState 익히기' 이후 컴포넌트를 분리하고 스타일링하기
- Mission2 - 영화 컴포넌트 만들기

### 📝 To-do

- Mission1
- [x]  컴포넌트 분리를 해주세요
    - [x]  Button 컴포넌트
    - [x]  Input 컴포넌트
- [x]  본인만의 TODO List 스타일링을 추가해주세요.
    - [x]  `inline` 스타일링이 아닌, `className`을 활용한 스타일링을 진행해주세요!
- Mission2
- [x] API 사용하기
- [x] 위의 API를 활용하여, 위와 동일한, 화면을 구현해주세요!
- [x] 영화 포스터에 마우스를 올려놓았을 때 아래와 같이, 검정 배경이 위에 보이는 처리를 해봅시다.

### 🔍 접근 방법

- Mission1
   - Button과 Input 컴포넌트를 분리했습니다.
  - 상태 관리를 위해 useState를 사용하여 할 일 목록과 입력 값을 관리했습니다.
  -  addTodo, deleteTodo, updateTodo와 같은 함수들을 통해 할 일을 추가, 삭제, 수정할 수 있도록 했습니다.
- Mission2
  - API를 활용하여 영화 데이터를 받아와 화면에 렌더링했습니다.
  - CSS Grid를 사용하여 영화 카드를 배치했습니다.
