### ISSUE TITLE
[ Week 4 ] 4주차 워크북 미션

### ISSUE THREAD

**Issue by hansoojeongsj** [DS-UMC-7th/UMC-7th-Chri#7]
### 🛠 Mission

1. 미션 1.  - Custom Hooks 실습
  chapter 3 미션을 진행하면서 데이터 요청을 할 때, 동일한 데이터 통신 코드를 불필요하게 반복 호출했던 문제를 해결하는 미션입니다. 반복되는 로직을 함수로 분리하여 재사용할 수 있도록 커스텀 훅을 만들어보는 것이 목표이고 이 커스텀 훅을 통해 로딩 및 에러 처리를 손쉽게 구현할 수 있도록 합니다. 

3. 미션 2. - 영화 상세 페이지 제작
미션 1을 바탕으로 영화 상세페이지를 만듭니다.

### 📝 To-do

1. 미션 1
  - [x]  이전에, 작성한 데이터를 받아오는 코드를, **`커스텀 훅을 활용`**해서, 리팩토링 해주세요!
  - [x]  **`loading`**, **`error`** 처리 또한 같이 해주세요!

2. 미션2
  - [x]  당 영화 컴포넌트를 클릭시, 상세 페이지로 이동하게 해주세요
      - [x]  경로는 **`/movies/:movieId` 로 이동되게 해주세요!**
  - [x]  **`movieId`**를 활용하여, 영화 상세 페이지 정보를 받아와주세요!
  - [x]  받은 내용을 바탕으로, 꼭 위의 방식으로, 디자인하지 않아도 좋습니다! 다만, **`CSS를 학습하며 멋지게 디자인`** 해주세요!
  - [x]  추가적으로, 감독/출연 데이터 또한 **`movieId`**를 활용하여, **`Credit 정보`**를 받아와주세요!
  - [x]  위에서, 실습한 **`custom-hook`**을 이용하여, **`loading`** 처리를 해주세요!
  - [x]  위에서, 실습한 **`custom-hook`**을 이용하여, **`error`** 처리를 해주세요!

### 🔍 접근 방법

- 첨부된 영상을 중심으로 코드를 작성했습니다.
- useCustomFetch를 커스텀 훅으로 작성하면 여러 컴포넌트에서 동일한 패턴으로 데이터를 가져올 수 있어 로직의 중복을 줄이고 코드의 일관성을 유지할 수 있도록 작성했습니다.
- axiosInstance를 별도로 설정해두면, 반복적으로 사용하는 기본 URL, 공통 헤더, 요청 인터셉터 등을 한 곳에 관리할 수 있도록 작성했습니다. 
- .env파일로 api토큰을 관리했습니다.
